import { Button, Col, Drawer, Layout, Menu, Row, theme } from "antd";
import Link from "next/link";
import Head from "next/head";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { MenuOutlined } from "@ant-design/icons";
const { Header, Content, Footer } = Layout;

const RootLayout = ({ children }) => {
  const {
    token: { colorBgContainer },
  } = theme.useToken();
  const [selectedKey, setSelectedKey] = useState("home");
  const [visible, setVisible] = useState(false);
  const router = useRouter();

  const paths = [
    {
      page: "Home",
      route: "/",
      Key: "home",
    },
    {
      page: "Universites",
      route: "/universities",
      Key: "universities",
    },
    {
      page: "About",
      route: "/about",
      Key: "about",
    },
    {
      page: "Services",
      route: "/services",
      Key: "services",
    },
    {
      page: "Contact",
      route: "/contact",
      Key: "contact",
    },
  ];

  const [open, setOpen] = useState(false);

  const showDrawer = () => {
    setOpen(true);
  };
  const onClose = () => {
    setOpen(false);
  };

  useEffect(() => {
    // Close the drawer when the path changes
    onClose();
  }, [router.asPath]);

  const handleMenuClick = (e) => {
    setSelectedKey(e.key);
  };

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout className="layout">
        <Header className={"header"}>
          <div className={"container   MainHead"}>
            <div className="">
              <Link href="/">
                <h1 className="logo">Sorted</h1>
              </Link>
            </div>

            <div className="">
              <div className="dextop">
                <Menu
                  onClick={handleMenuClick}
                  selectedKeys={[selectedKey]}
                  mode="horizontal"
                  style={{
                    display: "block",
                    backgroundColor: "transparent",
                  }}
                >
                  {paths.map((path, index) => (
                    <Menu.Item Key={path.Key}>
                      <Link
                        style={{
                          color: "white",
                          margin: "0px 18px",
                          fontSize: "28px",
                        }}
                        href={path.route}
                      >
                        {path.page}
                      </Link>
                    </Menu.Item>
                  ))}
                </Menu>
              </div>

              <div className={"mobileMenu "}>
                <Button className="custom-drawer-button" onClick={showDrawer}>
                  <MenuOutlined style={{ fontSize: "30px" }} />
                </Button>
                <Drawer placement="right" onClose={onClose} open={open}>
                  {paths.map((path, index) => (
                    <Link
                      className="MobileMenuLink"
                      style={{
                        textDecoration: "none",
                        lineHeight: "26px",
                        color: "black",
                      }}
                      key={index + 1}
                      href={path.route}
                    >
                      <p
                        className="MobileNavIteam"
                        style={{ fontSize: "35px" }}
                      >
                        {" "}
                        {path.page}
                      </p>
                    </Link>
                  ))}
                </Drawer>
              </div>
            </div>
          </div>
        </Header>
        <Content>
          <div
            className="site-layout-content"
            // style={{
            //     minHeight: "100vh",
            // }}
          >
            {children}
          </div>
        </Content>
        <Footer className="footer">
          <Content className={"container"}>
            <div className="footer-content">
              <div className="footer-left">
                <h2>SORTED EDUCATION HELP CENTER</h2>
              </div>
              <div className="footer-right">
                <h2>abdulla@sortededucation.com</h2>
              </div>
            </div>
          </Content>
        </Footer>
      </Layout>
    </>
  );
};
export default RootLayout;
