import Head from 'next/head'

import { Inter } from 'next/font/google'
import RootLayout from "@/components/Layouts/RootLayout";
import {Result} from "antd";
import {SmileOutlined} from "@ant-design/icons";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <Result
              icon={<SmileOutlined color='#6B1B1C!important'/>}
              title={<span style={{textTransform: 'uppercase', color: '#6B1B1C!important', fontWeight: 'bold'}}>We are under construction. Thank You!</span>}
          />
      </main>
    </>
  )
}

/*Home.getLayout = function getLayout(page) {
    return (
        <RootLayout>{page}</RootLayout>
    );
};*/
